trigger:
- master

pool:
  name: Agent_Windows_Branko  # Asegúrate de que este sea el nombre correcto de tu pool de agentes

variables:
  JAVA_HOME: 'C:\\Program Files\\Java\\jdk-11'

steps:
- checkout: self
  fetchDepth: 0

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
    npm install
    node app.js
  displayName: 'npm install and build'

- script: |
    echo "Setting JAVA_HOME"
    echo "##vso[task.setvariable variable=JAVA_HOME]C:\\Program Files\\Java\\jdk-11"
    echo "JAVA_HOME is now $(JAVA_HOME)"
  displayName: 'Set JAVA_HOME'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'modelodevopservicesprincipal'
    azureContainerRegistry: 'bosorio.azurecr.io'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Build services'
    additionalImageTags: 'az-img'
    qualifyImageNames: true
    includeLatestTag: true

- task: Docker@2
  inputs:
    containerRegistry: 'bosorio.azurecr.io'
    repository: 'az-imagetest'
    command: 'push'
    qualifyImageName: true
    includeLatestTag: true
    azureSubscriptionEndpoint: 'modelodevopservicesprincipal'
    displayName: 'Push Docker Image to ACR'
