trigger:
- master

pool:
  name: Agent_Windows_Branko  # Asegúrate de que este sea el nombre correcto de tu pool de agentes

variables:
  JAVA_HOME: 'C:\\Program Files\\Java\\jdk-11'

steps:
- checkout: self
  fetchDepth: 0

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
    npm install
    node app.js
  displayName: 'npm install and build'

