# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: Windows

steps:
- checkout: self
  fetchDepth: 0

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'brankoosorio'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'brankoosorio_node-mongo-app.git'
    cliProjectName: 'node-mongo-app.git'
    cliSources: '.'
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '14.x'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
    npm install
    node app.js
  displayName: 'npm install and build'

- script: |
    echo "Setting JAVA_HOME"
    set JAVA_HOME=C:\Program Files\Java\jdk-11
    echo "JAVA_HOME is now $JAVA_HOME"
  displayName: 'Set JAVA_HOME'
- task: SonarCloudAnalyze@1
  inputs:
    jdkversion: 'JAVA_HOME'
  
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish SonarCloud Report'
  