version: '3'

services:
  # Servicio de construcción
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app

  # Servicio de producción
  production:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    depends_on:
      - builder
